### ISSUE TITLE
Add missing Italian translations

### ISSUE THREAD

**Issue by frederik-elwert** [DiGArtefacts/thesaurus#1]
Some of the newly added concepts are still only in English. We should add Italian labels for these, too. (And also the ConceptScheme description, while we’re at it.)

**Comment by SerenaAutiero** [comment]
There are actually several concepts with no Italian label, here the stats:
![image](https://user-images.githubusercontent.com/108082631/178951767-7da62aef-1bdd-4cc6-8ca6-669d1b889133.png)

This will be progressively solved
