### ISSUE TITLE
New Concept: [cheek]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#102]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**cheek**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**body parts _(or: face parts, which was suggested)_**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
We already have it here: https://w3id.org/diga/terms/1313102966
