### ISSUE TITLE
New Concept: [foam]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#105]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**foam**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**setting (perhaps we should have a subcategory of "nature items" in "setting")"**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/3630579319
