### ISSUE TITLE
New Concept: [bank]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#106]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**bank**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**Setting**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
Do you mean river bank, right?

this is riverbank: https://w3id.org/diga/terms/5363936788

if it's correct please close the issue
