### ISSUE TITLE
General question: adjectives, setting depicitions

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#108]
Hi,

1. We would like to raise here the question of tagging adjectives, such as 'Golden,' 'Brilliant,' 'slender,' 'disgusting,' etc., repeating many times through the section we have just tagged about the sleeping women. Should we avoid tagging them since they are not explicitly discernible in visual artifacts? 

2. what about 'evening' or 'dusk'? Should we consider tagging it as part of the setting? Or- only tag actual objects that represent it in visual artifacts, such as 'moon'? 

3. adding new action concepts - should it be done here as a 'new tag' suggestion, or should it be done through another process?

**Comment by SerenaAutiero** [comment]
1 > see #109 
2 > for now I would only tag visual elements that accompany the identification of the time
3 > suggest "new tag", as soon as the onama labels are integrated then we can add the new actions we need
