### ISSUE TITLE
Add "criss-crossed chest ornament" & "chamber pot"

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#11]
DMC 933 -  Māyā's dream 

red arrow = Skr. channavīra / EN "criss-crossed chest ornament" / IT "ornamento pettorale incrociato" 

> option: EN with central medallion / IT con medaglione centrale

yellow arrow = "chamber pot" / IT "vaso da notte"

<img width="761" alt="Schermata 2022-07-14 alle 11 57 35" src="https://user-images.githubusercontent.com/108815325/178957704-2887c08a-6e7a-4fa5-b802-91b1d9c6c5b6.png">

**Comment by SerenaAutiero** [comment]
Re:  Skr. channavīra / EN "criss-crossed chest ornament" / IT "ornamento pettorale incrociato"

In the Thesaurus we have https://w3id.org/diga/terms/2801773867 that needs an update. We already discussed the terminology before, but now with the necessity to add this new concept that discussion needs to be updated. 
Instead of using "long cross-necklace [...]" we propose "transverse chest ornament"

**Comment by SerenaAutiero** [comment]
chamber pot --> https://w3id.org/diga/terms/6647489419

**Comment by SerenaAutiero** [comment]
@jessiepons Ask Peter about the sautoir necklace

**Comment by jessiepons** [comment]
That's Peter's response:

I wouldn’t consider this a sautoir necklace ( a term which I have just learned from you for the first time!). It criss-crossed between the breasts and is fastened at the back.  In classical contexts it’s less elegantly referred to as a ‘body-chain’.  See for example this real one: https://www.britishmuseum.org/collection/object/H_1994-0408-1 and https://www.lbma.org.uk/wonders-of-gold/items/hoxne-hoard-body-chain

They’re very interesting – the suggestion on that website that they have bridal associations is convincing – it’s hard to imagine that Romans didn’t associate them specifically with Venus/erotic connotations and they somehow don’t seem like everyday jewellery for a Roman matron!

**Comment by SerenaAutiero** [comment]
'body chain' as main label and 'criss-crossed chest ornament' as alternative?

**Comment by jessiepons** [comment]
sounds good to me

**Comment by cristiano-moscatelli** [comment]
The bridal association is interesting...

**Comment by SerenaAutiero** [comment]
Done: https://w3id.org/diga/terms/3063654775
