### ISSUE TITLE
Hand on shoulder

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#110]
DMC 124 - possibly Gods entreat the Buddha to preach? 
Hand on shoulder.

<img width="582" alt="Screenshot 2023-08-09 alle 12 27 14" src="https://github.com/DiGArtefacts/thesaurus/assets/108815325/e5906ee2-092b-40f6-9629-c2c719ab311c">

No idea on the meaning. Deference? 

@jessiepons @SerenaAutiero

**Comment by SerenaAutiero** [comment]
Inserted for the time being as [gesture of deference with one hand placed on the corresponding shoulder](https://w3id.org/diga/terms/9373949833)
Do we have comparisons for this gesture? I cannot find any, if so maybe we should opt for a more generic label

**Comment by SerenaAutiero** [comment]
Refer to [this](https://w3id.org/diga/terms/8664027827)
