### ISSUE TITLE
New Concept: [Himavat]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#112]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**Himavat**
Give the concept a main label in English.

**Himalaya**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**mountains-- **
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
[himavat](https://w3id.org/diga/terms/4972208499)
