### ISSUE TITLE
Change hierarchy: legged footstool

### ISSUE THREAD

**Issue by frederik-elwert** [DiGArtefacts/thesaurus#116]
The legged footstool <https://w3id.org/diga/terms/2153381679> is currently a sub-concept of the very specific motif "four legged backless throne, with figured legs". It also can appear as a generic piece of furniture, e.g., in [DMC 881](https://heidicon.ub.uni-heidelberg.de/#/detail/1712032). So we should add "furniture" as a `broaderGeneric` for legged footstool.

**Comment by SerenaAutiero** [comment]
Done!
