### ISSUE TITLE
pond

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#119]
E.g. DMC 650, naga couple emerging from a pond (here not carved) 
![DMC650-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/d15e3f6a-dee9-455b-8f7e-3b9a9e7e67cd)

**Comment by SerenaAutiero** [comment]
[pond](https://w3id.org/diga/terms/4730795019)
