### ISSUE TITLE
Add a, or modify "gesture of mourning"

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#13]
We have "gesture of mourning with left hand on cheek", but this is also performed with the right hand (see picture, DMC 945). 

Should we have two separate concepts, or modify what we have as  "left/right hand on cheek"?. 

<img width="166" alt="Schermata 2022-07-14 alle 17 02 48" src="https://user-images.githubusercontent.com/108815325/179014157-597cef2a-d5dc-4c42-847f-12e7591bb169.png">

**Comment by SerenaAutiero** [comment]
Modified in left/right > https://w3id.org/diga/terms/3957495203
