### ISSUE TITLE
New Concept: hermitage

### ISSUE THREAD

**Issue by Stepanmu** [DiGArtefacts/thesaurus#133]
location is either forest or hermitage

**Label**
hermitage

**Comment by SerenaAutiero** [comment]
Here is [hermitage](https://w3id.org/diga/terms/2891407508) under [minor architecture](https://w3id.org/diga/terms/1569179484). Technically "forest" should be used as general setting, while "hermitage" indicates the settlements, so when there are huts or other signs of anthropization
