### ISSUE TITLE
Check "filletted" 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#14]
"Filletted" seems to be wrong either in AE and BE, "filleted" is the correct one. We need to check it.

**Comment by SerenaAutiero** [comment]
Can you please point out in which concept this is spelled wrong? I searched in skosmos and vocbench with no results

**Comment by cristiano-moscatelli** [comment]
decorative motifs › composite decorative motifs › [geometric and phytomorphic decorative motifs](https://w3id.org/diga/terms/2587515604)

**Comment by SerenaAutiero** [comment]
Solved, there were actually many (originally from the Repertorio)
