### ISSUE TITLE
question: animals' body parts

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#141]
5.73: 73. His chine and rump and fetlocks were long, while his
hair, tail and ears were short and kept still; his back and flanks were depressed and raised, and the point of his nose, forehead,
haunches and chest were broad.

this is a depiction of the horse. Some of the body parts exist in the Thesaurus but are not specified as horse parts. Should we have different tags?

**Comment by SerenaAutiero** [comment]
I suggest to use those we already have and to add those we don't have under [animal: some general features](https://w3id.org/diga/terms/8476002685) if specific for animals, otherwise under [body parts](https://w3id.org/diga/terms/2483270731) (if the element is in common with humans)
