### ISSUE TITLE
New Concept: [banner/ flag]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#148]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**banner**
Give the concept a main label in English.

**flag**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**Suggested broader concepts**
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
Do I understand correctly that the concept "flag for contest" is not satisfying? 

Depending on the context in which the term appears, I can add "flag" as a broader category and banner as an alternative label for it. Does that sound reasonable?

**Comment by jessiepons** [comment]
@InbarMaor 
As I was updating VocBench, I noticed that we have "flag" as an alternative label for "flag for constest". Let me know whether you would be willing to use this concept. Otherwise, I could create a label "banner" under miscellaneous objects (with the uri 2074426122=

**Comment by InbarMaor** [comment]
great, so could we add "banner" as an additional alternative label of "flag for contests" ?  thank you!
@jessiepons

**Comment by jessiepons** [comment]
@InbarMaor I guess so. Unless you feel your banner is very specific and should have its own concept, I would add it as alternative label.

**Comment by jessiepons** [comment]
@InbarMaor Banner hast been added as alternative label. You should use this: https://w3id.org/diga/terms/1758990784
