### ISSUE TITLE
Errornous broaderInstatial relation

### ISSUE THREAD

**Issue by frederik-elwert** [DiGArtefacts/thesaurus#15]
This one slipped through, we generally don’t use that relation type: https://w3id.org/diga/terms/1976200582

**Comment by frederik-elwert** [comment]
This is used in a couple more places. We should check if they can be replaced by `broaderGeneric` or if there was a specific motivation.

**Comment by SerenaAutiero** [comment]
All checked and replaced with `broaderGeneric`
