### ISSUE TITLE
New Concept: [akaniṣṭha] (in: celestial being)

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#153]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**akaniṣṭha**
Give the concept a main label in English.
(as a type of celestial beings)

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**Suggested broader concepts**
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
Added in the category "generic deities, etc...". Can you please explain what sort of deity this is?
URI: 9328856880
