### ISSUE TITLE
New Concept: [house]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#165]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**house**
Give the concept a main label in English.

**abode, place of refuge**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**setting**
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
@abigailpenn Here is the URI. 2816470495
