### ISSUE TITLE
New Concept: [fire]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#166]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**fire**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**natural elements? **
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
@abigailpenn here is the URI: 3616297088
