### ISSUE TITLE
New Concept: [to grasp]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#168]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**Label**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**verbs**
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
added to the Thesaurus: 1109266901
