### ISSUE TITLE
Check 'sumitra'

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#21]
https://w3id.org/diga/terms/1588656086

**Comment by cristiano-moscatelli** [comment]
According to online encyclopediae, it seems she was Sumitra or Bhadra in The Collective Sutra of the Buddha's Past Acts 佛本行集經, but I couldn't find the text. 

The Buddhist Dictionary of Pali Proper Names records "Sumittā" (https://www.palikanon.com/english/pali_names/dic_idx.html).

**Comment by cristiano-moscatelli** [comment]
we leave this out

**Comment by SerenaAutiero** [comment]
@cristiano-moscatelli @jessiepons 
I will then remove sumitra/sumitta from the Thesaurus, shall I put flower girl as generic figure? or  shall we find a way to have a flower girl indicating specifically that one flower girl?

**Comment by cristiano-moscatelli** [comment]
> one other option is to keep her as a specific literary person with the description as label --> 'the woman who gave lotus flowers to Sumedha in the Dīpaṅkara legend'

I'd go with this one as she is indeed a specific figure

**Comment by cristiano-moscatelli** [comment]
Perhaps we should specify that the figure is Yaśodharā in a past life?

**Comment by SerenaAutiero** [comment]
This would be too much information imho

**Comment by jessiepons** [comment]
I agree, it's too much

**Comment by SerenaAutiero** [comment]
concept modified according to discussion
