### ISSUE TITLE
Sacrificial fire (nuptial)

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#25]
DiGA Day 6, DMC 849, Marriage of the Bodhisattva

sacrificial fire / homa 
circumambulation around the (nuptial) fire / agnipariṇayana

See G. Verardi (1991) Homa and other fire rituals ... pp. 4 ff. 

![DMC849-1](https://user-images.githubusercontent.com/108815325/199539641-b793787a-5a13-449f-8387-bed19cee2e66.jpeg)

**Comment by SerenaAutiero** [comment]
@cristiano-moscatelli @jessiepons
Under [wedding accessories](https://w3id.org/diga/terms/42039075) we already have [fire-place](https://w3id.org/diga/terms/936168583), I would add 'sacrificial' to the label for disambiguation.

As for 'circumambulation around the (nuptial) fire / agnipariṇayana', we have in the narratives [marriage of the bodhisattva](https://w3id.org/diga/terms/2598707406), which this one panel seems to correspond (cfr for example [BM panel](https://www.britishmuseum.org/collection/object/A_1950-0727-1)). Do we need a marriage scene also in [generic scenes](https://w3id.org/diga/terms/3450847079)?

**Comment by SerenaAutiero** [comment]
And [sacrificial fire place](https://w3id.org/diga/terms/936168583) is!

**Comment by jessiepons** [comment]
And I agree with you. If necessary, we can add "circumambulation around the nuptial fire" & "agniparinayana" as alternative labels.
