### ISSUE TITLE
solar disk on crescent moon

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#26]
DiGA Day 6, DMC 857, top of the object 

<img width="335" alt="Screenshot 2022-11-02 alle 17 04 08" src="https://user-images.githubusercontent.com/108815325/199540528-142ce44f-867a-4342-a453-e90fe3c5887e.png">

**Comment by SerenaAutiero** [comment]
[https://w3id.org/diga/terms/0488902640](https://w3id.org/diga/terms/0488902640)
