### ISSUE TITLE
Row of ovals (motif)

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#27]
DiGA Day 6, DMC 865, cornice 

<img width="943" alt="Screenshot 2022-11-02 alle 17 05 24" src="https://user-images.githubusercontent.com/108815325/199540969-b96f6ef0-ed43-4da8-9a55-ae202334fa70.png">

**Comment by SerenaAutiero** [comment]
Please @cristiano-moscatelli check Repertorio pl. 65, could it be a worn [row of dentils with same height and width](https://w3id.org/diga/terms/3920189273)?

**Comment by cristiano-moscatelli** [comment]
It could. The outlines look quite rounded to me, but maybe you're right.

**Comment by SerenaAutiero** [comment]
> It could. The outlines look quite rounded to me, but maybe you're right.

I mean if you remember it live, and also at the touch it's rounded ovals, then it's rounded ovals, I can add the concept anyways
