### ISSUE TITLE
Add new entries in the narrative section

### ISSUE THREAD

**Issue by jessiepons** [DiGArtefacts/thesaurus#28]
In light of our discussion with Monika & co. on Tuesday, we need to add the following to the Thesaurus:

- "Cutting a bunch of reeds" & "kalamacchedya" (as alternative label based on the Sanghabhedavastu, MSV). The episode appears after the wrestling competition in the Sanghabhedavastu

Do we also want to add "Buddha in a Cave"?

**Comment by SerenaAutiero** [comment]
Cutting a bunch of reeds --> [https://w3id.org/diga/terms/9459176676](https://w3id.org/diga/terms/9459176676)

**Comment by SerenaAutiero** [comment]
"buddha in a cave" --> [https://w3id.org/diga/terms/9120800481](https://w3id.org/diga/terms/9120800481)

**Comment by SerenaAutiero** [comment]
> "buddha in a cave" --> https://w3id.org/diga/terms/9120800481

I added this anyways because for fragments or for the false bracket/peg it makes sense to have it

**Comment by jessiepons** [comment]
Right now I have error messages when I look into the terms but... thank you!

**Comment by SerenaAutiero** [comment]
> Right now I have error messages when I look into the terms but... thank you!

You get the error from skosmos, they now exist in the editor (VocBench), at the next update they will appear also in skosmos

**Comment by jessiepons** [comment]
Makes sense...
