### ISSUE TITLE
Berry 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#29]
e.g. DMC 748

<img width="561" alt="Screenshot 2023-01-18 alle 16 05 17" src="https://user-images.githubusercontent.com/108815325/213206818-86e06ed5-2dc7-4d84-991c-b45b9d8ae3ce.png">

**Comment by SerenaAutiero** [comment]
[here](https://w3id.org/diga/terms/5447401427) as "branch of pipal with leaves and berries"
