### ISSUE TITLE
Row of half double concentric disks with a central half small circle 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#30]
DMC 747

<img width="561" alt="Screenshot 2023-01-18 alle 16 06 58" src="https://user-images.githubusercontent.com/108815325/213207554-e593be48-d8c6-460e-b844-2121870141b6.png">

**Comment by SerenaAutiero** [comment]
This type of moulding is usually called "roundel" or "medallion", I would suggest for the motif "row of half roundels with a concentric border". What do you think? @cristiano-moscatelli @jessiepons

**Comment by jessiepons** [comment]
I'd say "row of half roundels with a border". Since we have roundels, the concentric specification feels redundant. No?

**Comment by SerenaAutiero** [comment]
[Here!](https://w3id.org/diga/terms/9166923526)
