### ISSUE TITLE
row of oblique pearls within listels 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#31]
DMC 610

<img width="561" alt="Screenshot 2023-01-18 alle 16 09 35" src="https://user-images.githubusercontent.com/108815325/213208044-16807ee4-afb7-4e98-83b8-c702fd33146e.png">

**Comment by SerenaAutiero** [comment]
tortile motif with alternating patterns

oblique alternating wavy lines and rows of pearls within plain listels

@jessiepons

**Comment by jessiepons** [comment]
I'm tempted to use festoon here (based on the appearance of the motif on the garland Tav. 74 Repertorio). So something like:

Straight festoon with an alternating pattern of weaving lines and pearls between listels.

**Comment by SerenaAutiero** [comment]
Looking at the Repertorio better, I agree that festoon applies here

**Comment by SerenaAutiero** [comment]
[here!](https://w3id.org/diga/terms/6886420015)
