### ISSUE TITLE
row of straight, bordered ogival leaves 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#32]
DMC 573
<img width="548" alt="Screenshot 2023-01-18 alle 16 11 16" src="https://user-images.githubusercontent.com/108815325/213208633-7aa3490d-f49c-401f-bee9-e62db1a27622.png">

**Comment by SerenaAutiero** [comment]
row of ogival leaves pointing up?

**Comment by SerenaAutiero** [comment]
[here the "row of ogival leaves" hierarchy](https://w3id.org/diga/terms/8990981754)
