### ISSUE TITLE
balcony 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#33]
We have "balconies with arches (type) on columns, alternating with segmental triangular architrave; with railing-shaped parapet (or other type of motif)", I guess we need a more general entry. 

  
<img width="579" alt="Screenshot 2023-01-18 alle 16 15 26" src="https://user-images.githubusercontent.com/108815325/213209547-b4ab272c-c099-4c35-b090-49c0b7f070af.png">

**Comment by SerenaAutiero** [comment]
[Here!](https://w3id.org/diga/terms/5314168498)
