### ISSUE TITLE
double wavy line 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#34]
DMC 705

<img width="579" alt="Screenshot 2023-01-18 alle 16 17 24" src="https://user-images.githubusercontent.com/108815325/213210078-8022fdf7-14d9-4f92-87fa-0444293f3712.png">

**Comment by cristiano-moscatelli** [comment]
Jessie suggests: 

two superposed wavy lines? 
a double wavy strip
Two wavy strips?

**Comment by SerenaAutiero** [comment]
@cristiano-moscatelli  @jessiepons
could it correspond to [wavy pattern in the AAT](https://www.getty.edu/vow/AATFullDisplay?find=wavy+line&logic=AND&note=&english=N&prev_page=1&subjectid=300009936)?

**Comment by cristiano-moscatelli** [comment]
> @cristiano-moscatelli @jessiepons
> could it correspond to [wavy pattern in the AAT](https://www.getty.edu/vow/AATFullDisplay?find=wavy+line&logic=AND&note=&english=N&prev_page=1&subjectid=300009936)?

I think it could

**Comment by jessiepons** [comment]
I agree!

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/1386660779
