### ISSUE TITLE
portable mirror

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#35]
<img width="579" alt="Screenshot 2023-01-25 alle 15 18 16" src="https://user-images.githubusercontent.com/108815325/214587499-411e9e36-7820-480d-a9ff-23b7f8de3a19.png">

**Comment by SerenaAutiero** [comment]
Isn't "hand mirror" its most common name?

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/7818681383 (as hand mirror, but let me know if you prefer me to change it)
