### ISSUE TITLE
Variant of Net with oblique lines

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#37]
![DMC794-1 det](https://user-images.githubusercontent.com/108082631/219016034-9cc01d26-0b34-411f-850f-2b7f8816bd7c.jpeg)

in the Thesaurus we have:
![image](https://user-images.githubusercontent.com/108082631/219016137-4dba616c-75b5-4ad9-a62e-47e46f6eb4d9.png)

> [net with oblique lines](https://w3id.org/diga/terms/606471797)

Do we need to add a variant? Is that a simplification of [straight festoon with overlapping lanceolate leaves, facing right](https://w3id.org/diga/terms/19742819)?

I could create two variants of [net with oblique lines](https://w3id.org/diga/terms/606471797):
1) net with oblique lines crossing at right angle
2) net with oblique lines defining lozenges

Please note that in the Repertorio "festoon" is only used for phytomorphic decorative motifs

**Comment by cristiano-moscatelli** [comment]
It seems a simplification of the straight festoon. I'm fine with creating the two variants.

**Comment by cristiano-moscatelli** [comment]
It does seem a simplification of the straight festoon. 

What about net with lozenges?

**Comment by SerenaAutiero** [comment]
I just realised that I have used "straight festoon with lozenges" in at least another description, shall we go with this phrasing?

@jessiepons @cristiano-moscatelli

**Comment by jessiepons** [comment]
I think the connection to "festoon" (albeit a messed up one) should be maintained. I would opt for a more simple option "straight festoon" but I'm fine with "straight festoon with lozenges"

**Comment by cristiano-moscatelli** [comment]
I'm fine with either term

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/5949131811
