### ISSUE TITLE
Row of thunderbolts?

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#38]
![DMC1225-1 copy](https://user-images.githubusercontent.com/108082631/219017887-5959596c-a377-47b2-93fa-ca6841a53d94.jpeg)

Attested in DMC 1225 and DMC 1230 (where is in bad conditions and left doubts about the identification of the motif)

@jessiepons and @cristiano-moscatelli suggestions on the label?

**Comment by cristiano-moscatelli** [comment]
I think it's just a row of (continuous) chevrons (Repertorio Pl. 66, n. 1)

[google images](https://www.google.com/search?q=chevrons+motif&client=safari&hl=it&sxsrf=AJOqlzVYohZloS7AYM9bzlGqitj8TzIr3Q:1676478239744&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi6i9CP-Jf9AhUVR_EDHVOBAWcQ_AUoAXoECAEQAw&biw=1440&bih=820&dpr=2l)

**Comment by SerenaAutiero** [comment]
in DMC 916 we have a row of chevrons, this one looks different, but it's ok if they need to be assimilated.

chevrons: 
![image](https://user-images.githubusercontent.com/108082631/219093860-4a69e330-d934-4d84-ab8c-b9164d28aac5.png)

DMC1225-1230:
![motif zigzag](https://user-images.githubusercontent.com/108082631/219096021-caad0af6-0c4b-4638-805d-f177c2046a41.jpg)

**Comment by jessiepons** [comment]
how about "row of vertical zigzags"?

**Comment by SerenaAutiero** [comment]
@jessiepons @cristiano-moscatelli 
I did not find any better way of describing this, "row of sowilo-like symbols" could result cryptic to many. I would go with "row of vertical zigzags" then.
The entry is [here](https://w3id.org/diga/terms/4207465409), of course we can still modify the label if a better idea comes out

**Comment by jessiepons** [comment]
I'm fine with this
