### ISSUE TITLE
Siddhartha in the gynaeceum

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#39]
Based on comparisons from Jessie's catalog, the left scene in DMC 791 (Day 5) displays Siddhartha in the gynaeceum. Do you agree? We have to add this to the list of narratives on Skosmos. 

I would avoid the term gynaeceum. Olivelle's translation of the related Canto (no. II) has "ladies' chambers". What do you think? 

@SerenaAutiero @jessiepons 
<img width="733" alt="Screenshot 2023-02-15 alle 15 03 49" src="https://user-images.githubusercontent.com/108815325/219050243-b00e0026-a7fe-4a07-8b77-297c97dc71b9.png">
<img width="584" alt="Screenshot 2023-02-15 alle 15 09 07" src="https://user-images.githubusercontent.com/108815325/219050307-815890d0-127a-42b0-91e6-2aca79b261d6.png">

**Comment by SerenaAutiero** [comment]
I definitely agree with the identification. This scene would fall under [life in the palace](https://w3id.org/diga/terms/2721284326), we can create a sub-episode as 'siddhartha in the ladies' chambers' or 'siddhartha in the ladies' quarters'

**Comment by jessiepons** [comment]
Wait, isn't this what is meant by "life in the palace" in the first place. The terms also listed for this are: 

- life in the harem
- palace scenes
- the bodhisattva in his palace with his wife and musicians

Perhaps we could simply add other alternative labels which you suggest: 

'siddhartha in the ladies' chambers' or 'siddhartha in the ladies' quarters' or 'siddhartha in the women's quarters

Alternatively, we could substitute "life in the palace" with another of these more specific terms. 

What do you think?

**Comment by cristiano-moscatelli** [comment]
Right. Sorry, I somehow missed them. 

I think "Life in the Palace" is too much generic, this is a quite specific scene. I'd go with "Siddhārtha in the women's quarter/chambers".

**Comment by jessiepons** [comment]
should we also check this section together to avoid any confusion?

**Comment by SerenaAutiero** [comment]
added alternative labels, fixed `prefLabel` in "siddhārtha in the women's quarter/chambers"
