### ISSUE TITLE
Make a distinction between Hariti and Hariti-like figures

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#4]
The identification of those female figures with fangs and a trident as Hariti is still a matter of debate. I suggest making a distinction between the two. 

See e.g. [https://www.academia.edu/44899498/Dangerous_Devis_Bad_Mothers_matrkas_and_Child_Snatchers_balagrahas_ ](url)

**Comment by SerenaAutiero** [comment]
create: ferocious female deity

**Comment by SerenaAutiero** [comment]
--> https://w3id.org/diga/terms/3304683163
