### ISSUE TITLE
namaskāramudrā

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#40]
@jessiepons @SerenaAutiero 

The term [namaskāramudrā](https://skosmos.ub.rub.de/thesaurus/en/page/1148676900) to indicate the palm of the right hand turned inwards at shoulder, chest height is wrong. 

See Luczanits, C. (2005) [The Bodhisattva with the Flask in Gandharan Narrative Scenes: In Memoriam Maurizio Taddei](http://luczanits.net/pdf/Luczanits%202005%20MaitreyaLife.pdf). EW 55, 1/4: 163-186. 

<img width="865" alt="Screenshot 2023-03-13 alle 11 31 14" src="https://user-images.githubusercontent.com/108815325/224676506-551b95a8-0530-4cae-a88a-673a5848b8bc.png">

It seems this mudrā is yet to be properly identified.

**Comment by SerenaAutiero** [comment]
I removed [namaskāramudrā](https://skosmos.ub.rub.de/thesaurus/en/page/1148676900) as alternative label and only left the explicatory ones
