### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by jessiepons** [DiGArtefacts/thesaurus#41]
As discussed during the meeting with Abigail / Roy, this category overlaps with the category "setting" we were thinking of adding. Should we label it:

- [ ] landscape
- [ ] setting
- [ ] landscape, setting

?

The following concepts should be added:

- [ ] sun
- [ ] cloud
- [ ] forest
- [ ] road

Should the following be added in the category landscape or architecture?

- [ ] palace
- [ ] courtyard

**Comment by jessiepons** [comment]
ok, when would you like to do that?

**Comment by SerenaAutiero** [comment]
Tomorrow Apr 4th, around 14:00/15:00?
