### ISSUE TITLE
Animals

### ISSUE THREAD

**Issue by jessiepons** [DiGArtefacts/thesaurus#42]
If we all agree, we can add a section "animal: some general features" to the category animals. Suggested concepts are:

- [ ] tail
- [ ] mane
- [ ] hoof
- [ ] trunk
- [ ] tusk
- [ ] horn

The alternative would be to have these concepts under the respective animals.

What do you think?

**Comment by SerenaAutiero** [comment]
To avoid double or repetitive labels I suggest a generic "animal: some general features" section and when tagging we can associate the tag of the specific animal.

The section is [here](https://w3id.org/diga/terms/8476002685)
