### ISSUE TITLE
	row of alternating vertical acanthus tufts and rosettes

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#47]
![DMC503-1](https://user-images.githubusercontent.com/108082631/229050897-cd3324a6-3c74-46cc-abfa-ee62afe16b4d.jpeg)

This is present in DMC503 and DMC570

**Comment by SerenaAutiero** [comment]
@cristiano-moscatelli @jessiepons

**Comment by cristiano-moscatelli** [comment]
I'm fine with it

**Comment by jessiepons** [comment]
me too

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/9811978494
