### ISSUE TITLE
	head band with two rows of squares DMC439

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#48]
![DMC439-1 copy](https://user-images.githubusercontent.com/108082631/229051791-636a55f4-1279-419f-94ec-1178ca4cffe0.jpg)

At least I need a better label 

@cristiano-moscatelli @jessiepons

**Comment by cristiano-moscatelli** [comment]
Headband with two strings of stones?

**Comment by jessiepons** [comment]
with two raws of square panels? pl. 67

**Comment by cristiano-moscatelli** [comment]
> with two raws of square panels? pl. 67
> 
> or headband with two strings of square stones?

I'd go with your second suggestion

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/2815545976
