### ISSUE TITLE
Row of pipal leaves and parallel pearls

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#49]
DMC 532

<img width="1091" alt="Screenshot 2023-04-03 alle 01 24 58" src="https://user-images.githubusercontent.com/108815325/229384793-7ba0edcc-d494-45e4-8d31-7ac1a9d48b07.png">

@SerenaAutiero @jessiepons

**Comment by jessiepons** [comment]
I think it's supposed to be a "sheaf" as in "Row of rosette-and-sheaf", pl. 77. So: "Row of pipal leaves-and-sheaf"?

**Comment by SerenaAutiero** [comment]
> I think it's supposed to be a "sheaf" as in "Row of rosette-and-sheaf", pl. 77. So: "Row of pipal leaves-and-sheaf"?

I agree that this could be the intention, but adding this to the Th and using as descriptor would be too speculative I think. Should we think of a more generic phrasing? Row of reclined cordate leaves with intermediate (filling) elements?

**Comment by jessiepons** [comment]
I think "reclined cordate leaves" is a bit of a mouthful (but perhaps that's already in the Repertorio?). On the one hand I do see pipal leaves and on the other hand, I do see the problem of adding a new label in the thesaurus for which we don't have a secure example. Perhaps:
- pipal leaves with intermediate element ?

**Comment by cristiano-moscatelli** [comment]
> I think "reclined cordate leaves" is a bit of a mouthful (but perhaps that's already in the Repertorio?). On the one hand I do see pipal leaves and on the other hand, I do see the problem of adding a new label in the thesaurus for which we don't have a secure example. Perhaps:
> 
> * pipal leaves with intermediate element ?

I'm fine with this. I would just add "pipal leaves with intermediate circular element"

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/0209474923
