### ISSUE TITLE
Discuss "monstrous" for goat-headed figures 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#5]
I feel "monstrous" describes the way we see them. I would rather define them as "goat-headed deities" (they are deities, although we don't know their names) or simply as "goat-headed figures".

**Comment by SerenaAutiero** [comment]
The original label derives from the Repertorio where goat-headed and boar-headed figures are both under `monstrous figures`. We already agreed on moving these figures to `theriomorphic figures` instead. 
I removed the adj monstrous from both, let me know if we can consider the issue closed or need further actions

**Comment by cristiano-moscatelli** [comment]
My mistake, sorry, I just confused the two terms (semi-divine theriomorphic-headed figure and the other therianthropic figures). 

Regarding the first, wouldn't it be better to label them as "semi-divine goat-headed figures"?

**Comment by SerenaAutiero** [comment]
It's already under `generic deities, spirits, mythological figures`, I would keep the label as it is also to avoid making it too long
