### ISSUE TITLE
row of upright ogival leaves and ?

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#50]
<img width="712" alt="Screenshot 2023-04-03 alle 02 04 10" src="https://user-images.githubusercontent.com/108815325/229386353-1ae6dc62-d710-48af-8c3c-07f3d45a8d94.png">

DMC 540

**Comment by cristiano-moscatelli** [comment]
@SerenaAutiero @jessiepons

**Comment by jessiepons** [comment]
leaf-and-dart? (pl. 76)

**Comment by cristiano-moscatelli** [comment]
No, it's a different motif to me. It seems there is a small leaf between the bigger ones

**Comment by SerenaAutiero** [comment]
Looks like a leaf-and-dart motif, but the ogival leaf is not bordered (therefore is different from Pl. 76, 4)

**Comment by jessiepons** [comment]
would you say it's the sepal of the flower? see Pl. 72.

**Comment by cristiano-moscatelli** [comment]
> 

Possibly, but I'm not sure

**Comment by SerenaAutiero** [comment]
@jessiepons @cristiano-moscatelli 
We never closed this one, reviewing it what if the repeated element is the one highlighted? Therefore a simplified version of a row of acanthus tufts?

![DMC540 motif](https://github.com/DiGArtefacts/thesaurus/assets/108082631/7052cf1f-a087-4ad1-a582-920083082da2)

**Comment by SerenaAutiero** [comment]
[It's most probably a bad rendering of row of carenated [upright] leaf-and-dar](https://w3id.org/diga/terms/4006991795)
