### ISSUE TITLE
Row of continuous disks DMC433

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#51]
![DMC433-1](https://user-images.githubusercontent.com/108082631/229441214-ba237763-9723-4c5d-bffd-144f9aa41f5c.jpeg)

**Comment by jessiepons** [comment]
Row of tangential pearls? See Repertorio pl. 64

or if you don't think these are pearls:

Row of tangential disks (to use the "tangential" of the Repertorio)

**Comment by cristiano-moscatelli** [comment]
To me these are pearls

**Comment by SerenaAutiero** [comment]
Referring to Pl. 64, I infer a difference in proportion between disks and pearls, the latter being smaller. In the case of DMC433, the roundels are proportionally quite large. Moreover I tend to consider pearls as having a half-sphere shape, not the shape of a flat roundel. If this is me being over-analytic, let's go with string of pearls.

**Comment by jessiepons** [comment]
I agree that the proportion is quite large for pearls but it's difficult to tell from the picture whether they are flat or bulbous like pearls. Do you think it's worth checking in Chakdara? Or we just go with one of the two (e.g. pearls)

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/9725071245
