### ISSUE TITLE
Nimbus with radiate border DMC433

### ISSUE THREAD

**Issue by SerenaAutiero** [DiGArtefacts/thesaurus#52]
![DMC433-1](https://user-images.githubusercontent.com/108082631/229442811-027d4115-4937-4e97-b2e6-31748c5a98d6.jpeg)

**Comment by cristiano-moscatelli** [comment]
Agree, I'd go with nimbus with border of saw-teeth

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/1328626445
