### ISSUE TITLE
New Concept: [lord]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#57]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**lord**
Give the concept a main label in English.

**master;bhartṛ**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**buddha epithets? general figures?**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
The concept is here: https://w3id.org/diga/terms/2961081343

we need to discuss during the meeting if and how we need to specify this is an epithet of the Buddha
@jessiepons
