### ISSUE TITLE
New Concept: [chest]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#58]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**chest**
Give the concept a main label in English.

**breast**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**some general features/body parts**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/6717877383

**Comment by abigailpenn** [comment]
link doesn't work
