### ISSUE TITLE
New Concept: [kamala lotus]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#59]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**kamala lotus**
Give the concept a main label in English.

*kamala**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**decorative motifs > phytomorphic decorative motifs > components of phytomorphic decorative motifs > lotus--lotus names**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
Is this intended as a decorative motif or just as a vegetation element? In the latter case it should probably go under [vegetation](https://w3id.org/diga/terms/473170543)

Can we maybe list different types of lotus?

@jessiepons

**Comment by SerenaAutiero** [comment]
The category 'phytomorphic elements and components' now has a two parents: phytomorphic decorative elements and under vegetation. Under "lotus" there is [lotus types](https://w3id.org/diga/terms/5543148585), where are collected the types proposed by @abigailpenn 

Please @jessiepons @cristiano-moscatelli check if it works for you

here [kamala](https://w3id.org/diga/terms/6335769914)

**Comment by SerenaAutiero** [comment]
See issue #117
