### ISSUE TITLE
New Concept: [hoof]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#60]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**hoof**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**animals > mammals > horse/horse body parts**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/5628399760
