### ISSUE TITLE
New Concept: [kapilavastu]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#62]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**kapilavastu**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**setting**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
[known places](https://w3id.org/diga/terms/8049973750)
- [kapilavastu](https://w3id.org/diga/terms/3617678015)

We need to discuss the parent label at the meeting
@jessiepons
