### ISSUE TITLE
New Concept: [panava]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#65]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**Panava drum** ****Kind of a drum- should we add as a concept under membraphones**?**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**[musical instruments> membranophones**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
**panava** is a variety of the **mridangam**, a barrel shaped wooden drum covered with skin on both sides, I suggest to tag in the BC as [barrel drum](https://w3id.org/diga/terms/933490939) 
@abigailpenn @jessiepons @cristiano-moscatelli 

ref: Krishnaswami, S. (2017). Musical instruments of India. Publications Division Ministry of Information & Broadcasting.
