### ISSUE TITLE
New Concept: [cord]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#66]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**cord**
Give the concept a main label in English.

**netting**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**part of a drum- maybe add under musical instrument's parts? **
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
shoulder strap: https://w3id.org/diga/terms/3722897584
(nested under 'miscellaneous objects' https://w3id.org/diga/terms/1020532692)
