### ISSUE TITLE
New Concept: [puṣkara (lotus)]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#67]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**Puṣkara**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**[decorative motifs]--[phytomorphic decorative motifs] > [components of phytomorphic decorative motifs] > lotus** **could different Sanskrit concepts for lotuses be included in Thes. under 'Lotus'? **
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/3362837049
