### ISSUE TITLE
Add gesture of listening (term & concept)

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#7]
DiGA Day 1, DMC 742

- figure: some general features
   - hand gesture
      - gesture indicating situations
         - gesture of listening with right hand holding left hand 
![Schermata 2022-07-07 alle 12 37 29](https://user-images.githubusercontent.com/108815325/177801339-d246cd46-0568-40f2-92a5-1f7a2ed21e42.jpg)

**Comment by SerenaAutiero** [comment]
Concept created: https://w3id.org/diga/terms/7644597466

**Comment by SerenaAutiero** [comment]
Solved
