### ISSUE TITLE
New Concept: [necklace]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#71]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**necklace**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**(figure: some general features > hair types > hair and ornaments of female indian type) 
**Thes. has only 'long necklace' or 'short necklace'- the type of necklace could not be indicated from text**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/6067891033

now the necklace types are under the more generic label 'necklace'
