### ISSUE TITLE
New Concept: [Lotus with a half curvd stalk]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#73]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**half-curved stalk**
Give the concept a main label in English.

**lotus with a half-curved stalk**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**[decorative motifs]> [phytomorphic decorative motifs] > [components of phytomorphic decorative motifs]> lotus**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/8888133384
