### ISSUE TITLE
New Concept: [big eyes]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#74]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**big eyes**
Give the concept a main label in English.

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**[figure: some general features]> [body parts](> [head]> [eye] > eye types**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/6805961446
