### ISSUE TITLE
Discuss and add the "hand on chin" gesture 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#8]
I've found it only once so far (DMC 836, see figure). 

<img width="185" alt="Schermata 2022-07-07 alle 16 40 14" src="https://user-images.githubusercontent.com/108815325/177801089-6fe189d1-ec57-48ec-97de-074e2d9af3da.png">

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/8422722699
