### ISSUE TITLE
Entries to be rephrased

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#80]
I think that some entries are redundant or need to be rephrased. 

In generic scenes › generic scenes with bodhisattva, we have:

- bodhisattva maitreya and donor(s)
- bodhisattva maitreya and devotee(s)
- bodhisattva with donor(s) and/or devotee(s)

While in generic scenes › generic scenes with buddha, we only have:

- buddha and devotee(s)
- buddha and donor(s)

I suggest having the following ones:

- bodhisattva maitreya with donor(s) and/or devotee(s)
- buddha with donor(s) and/or devotee(s)
- bodhisattva with donor(s) and/or devotees

What do you think? @SerenaAutiero @jessiepons

**Comment by jessiepons** [comment]
I agree, this makes more sense. I only think that "bodhisattva maitreya with donor(s) and/or devotee(s)" should be a narrower concept of "bodhisattva with donor(s) and/or devotees". 

Should we also have "buddha and bodhisattva with donor(s) and/or devotee(s)" to tag reliefs where both appear or simply tag with with two tags: buddha with donor(s) and/or devotee(s) + bodhisattva with donor(s) and/or devotees?

**Comment by SerenaAutiero** [comment]
Yes, I agree, I restructured the section following your lead

"Should we also have "buddha and bodhisattva with donor(s) and/or devotee(s)" to tag reliefs where both appear or simply tag with with two tags: buddha with donor(s) and/or devotee(s) + bodhisattva with donor(s) and/or devotees?" >>> done
