### ISSUE TITLE
Wrapped in the overrobe [with exposed toes of the left foot]

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#81]
Wrapped in the overrobe [with exposed toes of the left foot]

![DMC001-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/53c7b3ac-da3f-4737-a15f-b257f15ea012)

DMC 001

@SerenaAutiero @jessiepons

**Comment by jessiepons** [comment]
Keep it simple: Wrapped in the overrobe [with exposed left foot]

**Comment by cristiano-moscatelli** [comment]
I would have a term for this as the exposed toes of the left foot is a specific feature in late sculptural production. But if you want to keep it simple, I'm fine with this.

**Comment by SerenaAutiero** [comment]
I agree with Cristiano, this is the concept: [buddha wrapped in overrobe with exposed hands and left toes](https://w3id.org/diga/terms/2058920445)
