### ISSUE TITLE
DMC 737

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#82]
- straight festoon with overlapping lanceolate leaves facing left and tied by a double ribbon
- a central rosette encased between two vertical fillets and a leaf pointing downwards
- long necklace with  horned monster head endings facing a central stone

![DMC737-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/fc2fc44f-56ef-4dad-8ee9-f4b69c23b5c4)

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
"straight festoon with overlapping lanceolate leaves facing left and tied by a double ribbon"
=> I have no idea what you are referring to. 

"a central rosette encased between two vertical fillets and a leaf pointing downwards"
I don't see the leaves pointing downwards... Did you check Tissot? She has very detailled descriptions of the jewelry. Do we want to be so detailled though? How do we want to go about this? Be detailled in the description but more generic in the tagging? Or not at all?

**Comment by SerenaAutiero** [comment]
short flat-band necklace with phytomorphic decoration with a central rosette between two vertical fillets > https://w3id.org/diga/terms/5243078387

long necklace with horned monster head endings facing a central stone > no concepts to add, for tagging those we have are enough, for the description you can eventually go further in detail with the shape of the `figured necklace endings` 

straight festoon with overlapping lanceolate leaves facing left and tied by a double ribbon > what shall I look at?
