### ISSUE TITLE
covered coffer-type throne

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#83]
Any suggestion?

![DMC751-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/a3df0a03-f055-421c-962f-f223f0653c61)

Scene on the left, 'Return to Kapilavastu'

- covered coffer-type throne

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
You mean covered coffer-type throne? Or "coffer-type throne with canopy"? Both are fine with me.

**Comment by cristiano-moscatelli** [comment]
Yes (sorry!), I meant the first one.

**Comment by SerenaAutiero** [comment]
After Jessie agreed, I did as proposed: this is the new thesaurus entry [seat on the back of an elephant with canopy](https://w3id.org/diga/terms/7376571892)
