### ISSUE TITLE
Right hand closed to the mouth

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#85]
DMC 004 (wrongly numbered as DMC 003, to be corrected)

<img width="1067" alt="Screenshot 2023-07-03 alle 11 46 01" src="https://github.com/DiGArtefacts/thesaurus/assets/108815325/4555a7c0-811f-4f60-bc86-12509111df01">

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
Are you correcting the number?

What is the red arrow pointing to?

**Comment by cristiano-moscatelli** [comment]
Yes and yes (sorry for the mistake). 

Actually, looking at it again, it seems the hand was on the chin. Do you agree?

**Comment by jessiepons** [comment]
yes

**Comment by jessiepons** [comment]
yes I do!

**Comment by SerenaAutiero** [comment]
I also agree it's hand on the chin, therefore we already have it
