### ISSUE TITLE
Double plain string/ring

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#86]
DMC 221

![DMC221-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/ea9d8370-2774-46aa-86ca-aacde3950c1b)

@jessiepons @SerenaAutiero

**Comment by cristiano-moscatelli** [comment]
I'm referring to the double string/ring that ties the usnisa

**Comment by jessiepons** [comment]
Ok, then double string/ring at base of usnisa 
We might have to reshuffle the thesaurus as well...

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/0961924197
