### ISSUE TITLE
Row of half roundels with a border and central, tangential small circle

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#87]
DMC 557

- row of half roundels with a border and central, tangential small circle

<img width="1067" alt="Screenshot 2023-07-03 alle 11 49 30" src="https://github.com/DiGArtefacts/thesaurus/assets/108815325/088c041c-3502-40b1-9851-21feacf055de">

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
why not "row of half concentric disks" as the motif compares to the hair of DMC 597

**Comment by cristiano-moscatelli** [comment]
I reworked Repertorio: Pl. 64, no. 2, but I'm fine with your suggestion.

**Comment by SerenaAutiero** [comment]
We agreed to follow the lead of the Repertorio: https://w3id.org/diga/terms/3815557788
