### ISSUE TITLE
central not with row of concentric disks

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#88]
DMC 597:

- central knot with row of concentric disks

![DMC597-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/349ad588-ab01-4516-beca-c63f2a0a7a20)

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
row of concentric disks => ok
a crossed cord passing over the right armpit with kavacas => a crossed cord to right shoulder with amulet boxes (kavacas)
(clearly the craftsman had no idea about what he was representing)

**Comment by SerenaAutiero** [comment]
hair with a central chignon of schematic stacked coils > https://w3id.org/diga/terms/6597633888
