### ISSUE TITLE
Wrapped in the overrobe [with covered feet]

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#90]
DMC 632

- Wrapped in the overrobe [with covered feet]

![DMC632-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/72a1c6fd-4162-4fa7-b676-10c71a18a814)

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
Yes. Same here, I think the structure for the garments is a little unclear and needs to be reworked a bit.

**Comment by SerenaAutiero** [comment]
This piece here corresponds to the entry [buddha wrapped in overrobe with exposed hands and covered feet](https://w3id.org/diga/terms/2732920964)
