### ISSUE TITLE
nipple / areola / row of opposite triangles separated by a vertical fillet 

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#91]
DMC 733:

- nipple
- areola
- row of opposite triangles separated by a vertical fillet (see necklace)

![DMC733-1](https://github.com/DiGArtefacts/thesaurus/assets/108815325/9bc8e127-1582-4bbf-a8c9-5dd4951117fe)

@jessiepons @SerenaAutiero

**Comment by jessiepons** [comment]
I would have two separate concepts for nipple and areola under "figures => body parts"
For the decoration of the necklace, it looks alright to me but check Tissot.

**Comment by SerenaAutiero** [comment]
nipple > https://w3id.org/diga/terms/8884373338
areola > https://w3id.org/diga/terms/5003933147

short flat-band necklace decorated with a row of opposite triangles forming squares separated by vertical fillets > https://w3id.org/diga/terms/1158705202

Please create one issue for each new suggested concept.
