### ISSUE TITLE
New Concept: [attendant]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#93]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**attendant**
Give the concept a main label in English.

**minister**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**[figures- generic persons**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/2547893027
