### ISSUE TITLE
New Concept: [mountain]

### ISSUE THREAD

**Issue by abigailpenn** [DiGArtefacts/thesaurus#96]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**mountain**
Give the concept a main label in English.

**mountain meru** *should different specific mountains be tagged*? 
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**setting**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/3846117522
