### ISSUE TITLE
New Concept: [diamond]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#98]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**diamond**
Give the concept a main label in English.

**gem**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**jewels and ornaments**
Specify an appropriate (existing) parent concept from the thesaurus.

**Comment by SerenaAutiero** [comment]
https://w3id.org/diga/terms/8896359836
